spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: petclinic
  jpa:
    hibernate:
      ddl-auto: none # MyBatis 사용 시 JPA 미사용 또는 참고용
    open-in-view: false
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:jmclinic}?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  messages:
    basename: messages/messages

  sql:
    init:
      mode: always # schema.sql, data.sql 실행

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: dev.spring.petclinic.domain
